import { types } from 'mobx-state-tree';
import { RepoModel } from './RepoModel';

export const UserDataModel = types.model('UserDataModel', {
  avatar_url: types.optional(types.string, ''),
  bio: types.maybeNull(types.string),
  blog: types.optional(types.string, ''),
  company: types.maybeNull(types.string),
  created_at: types.optional(types.string, ''),
  email: types.maybeNull(types.string),
  events_url: types.optional(types.string, ''),
  followers: types.optional(types.number, 0),
  followers_url: types.optional(types.string, ''),
  following: types.optional(types.number, 0),
  following_url: types.optional(types.string, ''),
  gists_url: types.optional(types.string, ''),
  gravatar_id: types.optional(types.string, ''),
  hireable: types.maybeNull(types.boolean),
  html_url: types.optional(types.string, ''),
  id: types.optional(types.number, 0),
  location: types.maybeNull(types.string),
  login: types.optional(types.string, ''),
  name: types.maybeNull(types.string),
  node_id: types.optional(types.string, ''),
  organizations_url: types.optional(types.string, ''),
  public_gists: types.optional(types.number, 0),
  public_repos: types.optional(types.number, 0),
  received_events_url: types.optional(types.string, ''),
  repos_url: types.optional(types.string, ''),
  site_admin: types.optional(types.boolean, false),
  starred_url: types.optional(types.string, ''),
  subscriptions_url: types.optional(types.string, ''),
  twitter_username: types.maybeNull(types.string),
  type: types.optional(types.string, ''),
  updated_at: types.optional(types.string, ''),
  url: types.optional(types.string, ''),
  repos: types.array(RepoModel),
});
